name: Promote

on:
  pull_request:
    types:
    - closed
    - opened
    - synchronize
    branches: ["main"]


jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
    - uses: Oded-B/telefonistka-action@main
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
